---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: SB-Ecom-App-Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      color: blue
  template:
    metadata: null
    name: SB-Ecom-App-Pods
    labels:
      color: blue
  spec:
    containers:
      - name: SB-Ecom-App-Container
        image: websurf500/sb-ecom-app
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: SB-Ecom-App-Service
spec:
  type: LoadBalancer
  selector:
    color: blue
  ports:
    - port: 80
      targetPort: 8080
...
